### ISSUE TITLE
Prod tests VS mvp tetsts

### ISSUE THREAD

**Issue by hamdijmii1992** [rojala/ROjal_MQTT_Client#2]
The mvp_test_pubsub is OK, but I cannot make the prod_test_pubsub works.
When debugging the code I noticed that the prod_test_pubsub cannot send successive mqtt_ping_req messages, if the test try to send the second mqtt_ping_req message it receives a ServerUnvailable message error.

I am wondering also about difference between prod tests and mvp tests.
Further informaion: I am using Mmqtt (https://github.com/mmzeeman/mmqtt) as MQTT broker
Best regards.

**Comment by rjvo** [comment]
I need to test with Mmqtt broker to see what would go wrong - tested the implementation with Mosquitto and HiveMQ. Mean while it might be good to check with Wireshark (https://www.wireshark.org/) what is going between client and broker.  About mvp, it is first fully functional test using lower level API functions and higher level API is done based on the mvp tests, which make me to wonder why prod does not work (->bug?).

**Comment by hamdijmii1992** [comment]
@rjvo : In fact the problem come from the Mmqtt, it cannot handle packets with "cleanSession" attribute set to false
